/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Event;
import io.swagger.model.ModelApiResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.swagger.annotations.*;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.databind.ObjectMapper;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;

import java.io.IOException;
import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-02T21:58:31.998Z")

@Api(value = "event", description = "the event API")
@RequestMapping(value = "")
public interface EventApi {
    Logger log = LoggerFactory.getLogger(EventApi.class);
    
    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }
 
    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }
 
    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }
    @ApiOperation(value = "Add a new event to the seminar", nickname = "addEvent", notes = "Add a new event to the Seminar", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/event",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    default ResponseEntity<Event> addEvent(@ApiParam(value = "Events to be added to the seminar." ,required=true )  @Valid @RequestBody Event body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Deletes an event", nickname = "deleteEvent", notes = "", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Event not found") })
    @RequestMapping(value = "/event/{eventId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Event> deleteEvent(@ApiParam(value = "Event id to delete",required=true) @PathVariable("eventId") Long eventId, @ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Finds Events by status", nickname = "findEventsByStatus", notes = "Multiple status values can be provided with comma separated strings", response = Event.class, responseContainer = "List", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Event.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value") })
    @RequestMapping(value = "/event/findByStatus",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Event>> findEventsByStatus(@NotNull @ApiParam(value = "Status values that need to be considered for filter", required = true, allowableValues = "available, pending, sold") @Valid @RequestParam(value = "status", required = true) List<String> status) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/xml")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("<Event>  <id>123456789</id>  <name>Training 1</name>  <description>The first added training session by a trainer added to the event, which will take place on ... at the hour ...</description>  <photoUrls>    <photoUrls>aeiou</photoUrls>  </photoUrls>  <tags>  </tags>  <status>aeiou</status>  <date>15.03.2020 15:00</date>  <room>Room 111</room>  <trainer>Kamila Rolla</trainer></Event>", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/xml", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"date\" : \"15.03.2020 15:00\",  \"photoUrls\" : [ \"photoUrls\", \"photoUrls\" ],  \"trainer\" : \"Kamila Rolla\",  \"name\" : \"Training 1\",  \"description\" : \"The first added training session by a trainer added to the event, which will take place on ... at the hour ...\",  \"id\" : 0,  \"category\" : {    \"name\" : \"name\",    \"id\" : 6  },  \"room\" : \"Room 111\",  \"tags\" : [ {    \"name\" : \"name\",    \"id\" : 1  }, {    \"name\" : \"name\",    \"id\" : 1  } ],  \"status\" : \"available\"}, {  \"date\" : \"15.03.2020 15:00\",  \"photoUrls\" : [ \"photoUrls\", \"photoUrls\" ],  \"trainer\" : \"Kamila Rolla\",  \"name\" : \"Training 1\",  \"description\" : \"The first added training session by a trainer added to the event, which will take place on ... at the hour ...\",  \"id\" : 0,  \"category\" : {    \"name\" : \"name\",    \"id\" : 6  },  \"room\" : \"Room 111\",  \"tags\" : [ {    \"name\" : \"name\",    \"id\" : 1  }, {    \"name\" : \"name\",    \"id\" : 1  } ],  \"status\" : \"available\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Finds Events by tags", nickname = "findEventsByTags", notes = "Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.", response = Event.class, responseContainer = "List", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Event.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid tag value") })
    @RequestMapping(value = "/event/findByTags",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Event>> findEventsByTags(@NotNull @ApiParam(value = "Tags to filter by", required = true) @Valid @RequestParam(value = "tags", required = true) List<String> tags) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/xml")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("<Event>  <id>123456789</id>  <name>Training 1</name>  <description>The first added training session by a trainer added to the event, which will take place on ... at the hour ...</description>  <photoUrls>    <photoUrls>aeiou</photoUrls>  </photoUrls>  <tags>  </tags>  <status>aeiou</status>  <date>15.03.2020 15:00</date>  <room>Room 111</room>  <trainer>Kamila Rolla</trainer></Event>", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/xml", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {  \"date\" : \"15.03.2020 15:00\",  \"photoUrls\" : [ \"photoUrls\", \"photoUrls\" ],  \"trainer\" : \"Kamila Rolla\",  \"name\" : \"Training 1\",  \"description\" : \"The first added training session by a trainer added to the event, which will take place on ... at the hour ...\",  \"id\" : 0,  \"category\" : {    \"name\" : \"name\",    \"id\" : 6  },  \"room\" : \"Room 111\",  \"tags\" : [ {    \"name\" : \"name\",    \"id\" : 1  }, {    \"name\" : \"name\",    \"id\" : 1  } ],  \"status\" : \"available\"}, {  \"date\" : \"15.03.2020 15:00\",  \"photoUrls\" : [ \"photoUrls\", \"photoUrls\" ],  \"trainer\" : \"Kamila Rolla\",  \"name\" : \"Training 1\",  \"description\" : \"The first added training session by a trainer added to the event, which will take place on ... at the hour ...\",  \"id\" : 0,  \"category\" : {    \"name\" : \"name\",    \"id\" : 6  },  \"room\" : \"Room 111\",  \"tags\" : [ {    \"name\" : \"name\",    \"id\" : 1  }, {    \"name\" : \"name\",    \"id\" : 1  } ],  \"status\" : \"available\"} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Find event by ID", nickname = "getEventById", notes = "Returns a single event", response = Event.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Event.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Event not found") })
    @RequestMapping(value = "/event/{eventId}",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Event> getEventById(@ApiParam(value = "ID of event to return",required=true) @PathVariable("eventId") Long eventId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/xml")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("<Event>  <id>123456789</id>  <name>Training 1</name>  <description>The first added training session by a trainer added to the event, which will take place on ... at the hour ...</description>  <photoUrls>    <photoUrls>aeiou</photoUrls>  </photoUrls>  <tags>  </tags>  <status>aeiou</status>  <date>15.03.2020 15:00</date>  <room>Room 111</room>  <trainer>Kamila Rolla</trainer></Event>", Event.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/xml", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"date\" : \"15.03.2020 15:00\",  \"photoUrls\" : [ \"photoUrls\", \"photoUrls\" ],  \"trainer\" : \"Kamila Rolla\",  \"name\" : \"Training 1\",  \"description\" : \"The first added training session by a trainer added to the event, which will take place on ... at the hour ...\",  \"id\" : 0,  \"category\" : {    \"name\" : \"name\",    \"id\" : 6  },  \"room\" : \"Room 111\",  \"tags\" : [ {    \"name\" : \"name\",    \"id\" : 1  }, {    \"name\" : \"name\",    \"id\" : 1  } ],  \"status\" : \"available\"}", Event.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Update an existing event", nickname = "updateEvent", notes = "Change or add information about an existing event", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Event not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/event",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    default ResponseEntity<Event> updateEvent(@ApiParam(value = "Events that needs to be added to the Seminar" ,required=true )  @Valid @RequestBody Event body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Updates an Event in the Seminar with form data", nickname = "updateEventWithForm", notes = "", authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/event/{eventId}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> updateEventWithForm(@ApiParam(value = "ID of event that needs to be updated",required=true) @PathVariable("eventId") Long eventId,@ApiParam(value = "Updated name of the Event") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the Event") @RequestParam(value="status", required=false)  String status) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "uploads an image", nickname = "uploadFile", notes = "", response = ModelApiResponse.class, authorizations = {
        @Authorization(value = "seminar_auth", scopes = {
            @AuthorizationScope(scope = "write:events", description = "modify events in your account"),
            @AuthorizationScope(scope = "read:events", description = "read your events")
            })
    }, tags={ "Event", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class) })
    @RequestMapping(value = "/event/{eventId}/uploadImage",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    default ResponseEntity<ModelApiResponse> uploadFile(@ApiParam(value = "ID of event to update",required=true) @PathVariable("eventId") Long eventId,@ApiParam(value = "Additional data to pass to server") @RequestParam(value="additionalMetadata", required=false)  String additionalMetadata,@ApiParam(value = "file to upload") @Valid @RequestPart(value="file", required=false) MultipartFile file) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"code\" : 0,  \"type\" : \"type\",  \"message\" : \"message\"}", ModelApiResponse.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default EventApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
